paths:
  /auth/signup:
    post:
      tags:
        - Auth
      summary: User signup
      description: Creates a new user in the system.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                firstName:
                  type: string
                  description: First name of the user.
                lastName:
                  type: string
                  description: Last name of the user.
                email:
                  type: string
                  description: Email address of the user.
                phone:
                  type: string
                  description: Phone number of the user.
                address:
                  type: string
                  description: Address of the user.
      responses:
        '201':
          description: User created successfully
          content:
            application/json:
              schema:
        '400':
          description: Failed to create user
  /auth/send-otp:
    post:
      tags:
        - Auth
      summary: Send OTP
      description: Sends a One-Time Password (OTP) to the user's email for login.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  description: Email address to send the OTP.
                  example: mukulbkm1512@gmail.com
      responses:
        '200':
          description: OTP sent successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  otp:
                    type: string
                    description: Generated OTP.
        '404':
          description: User not found
  /auth/login:
    post:
      tags:
        - Auth
      summary: Login
      description: Verifies the OTP and logs the user in.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  description: Email address of the user.
                  example: mukulbkm1512@gmail.com
                otp:
                  type: string
                  description: One-Time Password (OTP) for authentication.
                  example: 123456
      responses:
        '200':
          description: Login successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
                    description: JWT token for authenticated requests.
        '401':
          description: Invalid OTP
  /auth/logout:
    delete:
      tags:
        - Auth
      summary: Logout
      description: Logs out the user by invalidating the token.
      security:
        - BearerAuth: []
      responses:
        '200':
          description: Logout successful
        '401':
          description: Unauthorized
