paths:
  /payments:
    post:
      tags:
        - Payments
      summary: Make a payment
      description: Initiates a payment for a given order.
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                orderId:
                  type: string
                  example: 456
                type:
                  type: string
                  enum:
                    - online
                    - cash-on-delivery
              required:
                - orderId
                - type
      responses:
        '201':
          description: Payment successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Payment successful
                  data:
        '400':
          description: Bad Request - Invalid input or payment failed
        '404':
          description: Not Found - Order not found
        '409':
          description: Conflict - Payment already made
